version: "3"
services:
    elasticsearch:
        image: "elasticsearch:7.2.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - elastic

    kibana:
        image: "kibana:7.2.0"
        ports:
            - "5601:5601"
#        environment:
#            ELASTICSEARCH_URL: "http://elasticsearch:9200"
#            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        networks:
            - elastic

    filebeat:
        image: "elastic/filebeat:7.2.0"
        user: root
        command: filebeat -e -strict.perms=false
        privileged: true
        volumes:
            - /tmp/files/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:Z
            - /var/lib/docker:/var/lib/docker:Z
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - elastic

volumes:
    elasticsearch_data:

networks:
  elastic:
    driver: bridge
