version: "3"
services:
    elasticsearch:
        image: "elasticsearch:7.2.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "kibana:7.2.0"
        ports:
            - "5601:5601"

    filebeat:
        image: "elastic/filebeat:7.2.0"
        user: root
        volumes:
            - /tmp/files/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:Z
            - /var/lib/docker:/var/lib/docker:Z
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    elasticsearch_data: